apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  volumes:
  - name: configmap-vol
    configMap:
      name: my-configmap
  containers:
  - name: test-container
    image: busybox
    command: [ "sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: configmap-vol
      mountPath: /etc/config
