apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "sh", "-c", "while true; do sleep 3600; done"]
    env:
    - name: BRANCH_FOR_MY_APP
      valueFrom:
        configMapKeyRef:
          name: test-cm
          key: branchName
    envFrom:
    - configMapRef:
        name: from-env-file
