apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web2-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: "*.192.168.189.128.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cats-svc
            port:
              number: 80
